import { Router } from 'express';
import * as transactionRepo from '../repositories/transactionRepository';
import * as recurringRepo from '../repositories/recurringTransactionRepository';
import { HttpError } from '../middleware/errorHandler';

export const transactionsRouter = Router();

// A transaction spawned from a still-active recurring series is locked —
// editing it means editing the template. Once the series is cancelled
// (active = 0), its already-generated transactions become directly
// editable again rather than staying locked forever.
function lockedByActiveSeries(recurringTransactionId: number | null): boolean {
  if (recurringTransactionId === null) return false;
  const series = recurringRepo.findById(recurringTransactionId);
  return series !== undefined && series.active === 1;
}

transactionsRouter.get('/', (_req, res) => {
  res.json(transactionRepo.findAll());
});

transactionsRouter.post('/', (req, res) => {
  const { amount, date, description, category_id } = req.body;

  if (typeof amount !== 'number') throw new HttpError(400, 'amount must be a number');
  if (typeof date !== 'string' || !date) throw new HttpError(400, 'date is required');
  if (typeof category_id !== 'number') throw new HttpError(400, 'category_id is required');

  const transaction = transactionRepo.create({ amount, date, description, category_id });
  res.status(201).json(transaction);
});

transactionsRouter.put('/:id', (req, res) => {
  const id = Number(req.params.id);
  const existing = transactionRepo.findById(id);
  if (!existing) throw new HttpError(404, 'Transaction not found');

  if (lockedByActiveSeries(existing.recurring_transaction_id)) {
    throw new HttpError(400, 'This transaction was generated by an active recurring series and must be edited via the template');
  }

  const { amount, date, description, category_id } = req.body;
  const transaction = transactionRepo.update(id, { amount, date, description, category_id });
  res.json(transaction);
});

transactionsRouter.delete('/:id', (req, res) => {
  const id = Number(req.params.id);
  const existing = transactionRepo.findById(id);
  if (!existing) throw new HttpError(404, 'Transaction not found');

  if (lockedByActiveSeries(existing.recurring_transaction_id)) {
    throw new HttpError(400, 'This transaction was generated by an active recurring series and must be removed via the template');
  }

  transactionRepo.remove(id);
  res.status(204).send();
});
